### ISSUE TITLE
Allow hybrid / auxiliary losses directly evaluated using backprop inside the model.

### ISSUE THREAD

**Issue by kfeeeeee** [chainer/chainerrl#117]
I am not sure if this is currently supported but I think it isn't.
Would it be possible to allow for hybrid losses, e.g. as it is used in this paper:

[Recurrent Models of Visual Attention](https://arxiv.org/abs/1406.6247)

The basic idea is to use for example REINFORCE for policy optimization while simultaniously optimizing a differentiable loss inside the model. 

It is possible to do so using plain chainer (see [ram.py])(https://github.com/amasky/ram/blob/master/ram.py)
but wrapping it up in chainerrl would be of benefit I guess.

**Comment by muupan** [comment]
Unfortunately, it's not supported for now. The current interface of Agent is not sufficient for such a usage. I think it is a good idea to support it because using RL (often REINFORCE) as a part of an optimization problem is common.

I think it is possible to allow it by extending the interface, say adding a method that just computes loss values to Agent.
