### ISSUE TITLE
Non-uniform architectures in Policy and Q-functions

### ISSUE THREAD

**Issue by xylee95** [chainer/chainerrl#407]
When using default policy and q-functions such as FCSAQFunction and FCDeterministicPolicy, is there a way to specify the networks such that they have a non-uniform architecture without defining a custom network? I.e., Having first layer with 256 hidden nodes, second layer with 512 nodes etc rather than specifying one argument for the whole network?

**Comment by muupan** [comment]
You can any `chainer.Link` as Q-function or Policy as long as it satisfies their input-output interface.

Instead of `FCSAQFunction`, you can use any `chainer.Link` that accepts batched observations and actions as input and outputs batched values.
```
def concat_obs_and_action(o, a):
    return F.concat((o, a), axis=1)

q_func = chainer.Sequential(
    concat_obs_and_action,
    L.Linear(obs_size + action_size, 512),
    F.relu,
    L.Linear(512, 256),
    F.relu,
    L.Linear(256, 1),
)
```

Instead of `FCDeterministicPolicy`, you can use any `chainer.Link` that accepts batched observations as input and outputs `chainerrl.distribution.Distribution`.
```
pi = chainer.Sequential(
    L.Linear(obs_size, 512),
    F.relu,
    L.Linear(512, 256),
    F.relu,
    L.Linear(256, action_size),
    chainerrl.distribution.ContinuousDeterministicDistribution,
)
```
