### ISSUE TITLE
bound_mean argument for A3CFFGaussian 

### ISSUE THREAD

**Issue by xylee95** [chainer/chainerrl#419]
Hello, I have another question.

I haven't tested this on any other agents yet, but I noticed that when I train a PPO agent on the environments BipedalWalker and LunarLander, the resulting sampled action is mostly out of the environment's action space even though the _bound_mean_ argument is set to **True**. 

The agent still turned out to be fine since there is a clipping function implemented for the environment but I was wondering if the argument  _bound_mean_ is meant for that? If it isn't, is there any way to restrict the agent so that the mean of the distribution returned is always within the action space?

**Comment by muupan** [comment]
`bound_mean=True` is meant to bound only the mean of a Gaussian policy, but samples from the policy can be out-of-bound even when the mean is inside the bound.

Suppose that the action space is [-1, 1] and the action distribution is N(0, 100). The mean is inside [-1, 1], while samples are almost always outside due to high variance.

**Comment by xylee95** [comment]
Thanks, that makes sense. If that is the case, is there a implementation or argument which limits the mean and the variance so that only samples within bounds can be sampled?
