### ISSUE TITLE
GPU does not work in train_a3c.py file

### ISSUE THREAD

**Issue by Ujwal2910** [chainer/chainerrl#563]
The file given here -https://github.com/chainer/chainerrl/tree/master/examples/atari/reproduction/a3c
which includes in the readme that using --gpu run the script with gpu, throws the following error-

usage: train_a3c.py [-h] [--processes PROCESSES] [--env ENV] [--seed SEED]
               [--outdir OUTDIR] [--t-max T_MAX] [--beta BETA] [--profile]
               [--steps STEPS] [--max-frames MAX_FRAMES] [--lr LR]
               [--eval-interval EVAL_INTERVAL] [--eval-n-steps EVAL_N_STEPS]
               [--weight-decay WEIGHT_DECAY] [--demo] [--load LOAD]
               [--logging-level LOGGING_LEVEL] [--render] [--monitor]
test.py: error: unrecognized arguments: --gpu

**Comment by prabhatnagarajan** [comment]
You're right! We'll remove that from the README. The original A3C didn't use GPUs, which is why we omitted it in the training file. We mistakenly also added the option to the README. If you'd like an example using a GPU, I would recommend our A2C example: https://github.com/chainer/chainerrl/blob/master/examples/atari/train_a2c_ale.py

**Comment by prabhatnagarajan** [comment]
No, A3C doesn't support updates on the GPU across several processes. A2C uses a single process to update the GPU.
